// DO NOT EDIT THIS FILE
// Created by xmlerator on Tuesday, 23 August 2016 at 04:12:29 PM.
#define OLYspeaker1_XML_VERSION 18

#ifndef __OLYspeaker1_DSPMAP_H__
#define __OLYspeaker1_DSPMAP_H__


typedef union Instance_t {							
	unsigned int uInst;								
	struct {											
		unsigned uType		: 8;		// type instance		
		unsigned uEffect	: 8;		// effect instance	
		unsigned uQual		: 16;		// qual instance	
	};												
} Instance_t;									

typedef struct _tParameterDesc_tag {						
	void (*fEditfunc)(void* vpValue, Instance_t tInst);		
	Instance_t tInst;										
} tParameterDesc;											

extern tParameterDesc g_tDeviceParameterTable[];
#define DEVICE_PARAMETER_MAX  41

extern tParameterDesc g_tStatusParameterTable[];
#define STATUS_PARAMETER_MAX  31

extern tParameterDesc g_tUserParameterTable[];
#define USER_PARAMETER_MAX  88

extern tParameterDesc g_tProfileParameterTable[];
#define PROFILE_PARAMETER_MAX  33

extern tParameterDesc g_tThrowParameterTable[];
#define THROW_PARAMETER_MAX  17

extern tParameterDesc g_tVoicingParameterTable[];
#define VOICING_PARAMETER_MAX  419

extern tParameterDesc g_tFirParameterTable[];
#define FIR_PARAMETER_MAX  1806

extern tParameterDesc g_tXoverParameterTable[];
#define XOVER_PARAMETER_MAX  7

extern tParameterDesc g_tAirlossParameterTable[];
#define AIRLOSS_PARAMETER_MAX  2

extern tParameterDesc g_tNoisegateParameterTable[];
#define NOISEGATE_PARAMETER_MAX  6

#endif	// __OLYspeaker1_DSPMAP_H__
