// DO NOT EDIT THIS FILE
// Created by xmlerator on Friday, 12 December 2014 at 06:05:53 PM.
#define OLYmixer1_XML_VERSION 7

#ifndef __OLYmixer1_PARAMLOOKUP_H__
#define __OLYmixer1_PARAMLOOKUP_H__


extern "C" {
#include "OLYmixer1_map.h"
}
#include "OLYmixer1_arch.h"
#include "OLYmixer1_pids.h"

typedef struct {
	int				eTarget;
	int				eParam;
	char*			pcParam;
	char*			pcOldParam;
} tLookupEntry;

extern tLookupEntry ParameterLookupTable[];
extern const int nLookupTableItems;

extern tParameterDesc* pParameterTables[eTARGET_FENCE];

#endif	// __OLYmixer1_PARAMLOOKUP_H__
