// DO NOT EDIT THIS FILE
// Created by xmlerator on Friday, 12 December 2014 at 06:05:53 PM.
#define OLYmixer1_XML_VERSION 7

#ifndef __OLYmixer1_DSPMAP_H__
#define __OLYmixer1_DSPMAP_H__


typedef struct _tParameterDesc_tag {						
	void (*fEditfunc)(void* vpValue, int iChan, int iAux);	
	int iChan;												
	int iAux;												
	int iFormat;												
	void* pvMin;												
	void* pvMax;												
	int linkedPID;											
} tParameterDesc;											

extern tParameterDesc g_tGlobalParameterTable[];
#define GLOBAL_PARAMETER_MAX  18

extern tParameterDesc g_tShowParameterTable[];
#define SHOW_PARAMETER_MAX  11

extern tParameterDesc g_tInfoParameterTable[];
#define INFO_PARAMETER_MAX  174

extern tParameterDesc g_tSnapshotParameterTable[];
#define SNAPSHOT_PARAMETER_MAX  501

#endif	// __OLYmixer1_DSPMAP_H__
