// DO NOT EDIT THIS FILE
// Created by xmlerator on Tuesday, 23 August 2016 at 04:12:29 PM.
#define OLYspeaker1_XML_VERSION 18


#include "OLY_meta.h"
#include "LOUD_enums.h"
#include "OLYspeaker1_meter.h"

LOUD_metertype g_OLYspeaker1MeterTypeTable[OLYspeaker1_METER_MAX] = {
	eMETERTYPE_NORMAL,				  //   0 eMID_OLYspeaker1_NULL
	eMETERTYPE_NORMAL,                //   1 eMID_OLYspeaker1_INPUT_IN
	eMETERTYPE_NORMAL,                //   2 eMID_OLYspeaker1_SPEAKER_IN
	eMETERTYPE_NORMAL,                //   3 eMID_OLYspeaker1_GROUP_SOFTLIMIT_IN
	eMETERTYPE_COMPGAINRED,           //   4 eMID_OLYspeaker1_GROUP_SOFTLIMIT_GAINREDUCE
	eMETERTYPE_NORMAL,                //   5 eMID_OLYspeaker1_GROUP_SOFTLIMIT_OUT
	eMETERTYPE_NORMAL,                //   6 eMID_OLYspeaker1_HF_OUT
	eMETERTYPE_NORMAL,                //   7 eMID_OLYspeaker1_HF_SOFTLIMIT_IN
	eMETERTYPE_COMPGAINRED,           //   8 eMID_OLYspeaker1_HF_SOFTLIMIT_GAINREDUCE
	eMETERTYPE_NORMAL,                //   9 eMID_OLYspeaker1_HF_SOFTLIMIT_OUT
	eMETERTYPE_NORMAL,                //  10 eMID_OLYspeaker1_HF_KLIMITER_IN
	eMETERTYPE_COMPGAINRED,           //  11 eMID_OLYspeaker1_HF_KLIMITER_GAINREDUCE
	eMETERTYPE_NORMAL,                //  12 eMID_OLYspeaker1_HF_KLIMITER_OUT
	eMETERTYPE_NORMAL,                //  13 eMID_OLYspeaker1_MF_OUT
	eMETERTYPE_NORMAL,                //  14 eMID_OLYspeaker1_MF_SOFTLIMIT_IN
	eMETERTYPE_COMPGAINRED,           //  15 eMID_OLYspeaker1_MF_SOFTLIMIT_GAINREDUCE
	eMETERTYPE_NORMAL,                //  16 eMID_OLYspeaker1_MF_SOFTLIMIT_OUT
	eMETERTYPE_NORMAL,                //  17 eMID_OLYspeaker1_MF_KLIMITER_IN
	eMETERTYPE_COMPGAINRED,           //  18 eMID_OLYspeaker1_MF_KLIMITER_GAINREDUCE
	eMETERTYPE_NORMAL,                //  19 eMID_OLYspeaker1_MF_KLIMITER_OUT
	eMETERTYPE_NORMAL,                //  20 eMID_OLYspeaker1_LF_OUT
	eMETERTYPE_NORMAL,                //  21 eMID_OLYspeaker1_LF_SOFTLIMIT_IN
	eMETERTYPE_COMPGAINRED,           //  22 eMID_OLYspeaker1_LF_SOFTLIMIT_GAINREDUCE
	eMETERTYPE_NORMAL,                //  23 eMID_OLYspeaker1_LF_SOFTLIMIT_OUT
	eMETERTYPE_NORMAL,                //  24 eMID_OLYspeaker1_LF_KLIMITER_IN
	eMETERTYPE_COMPGAINRED,           //  25 eMID_OLYspeaker1_LF_KLIMITER_GAINREDUCE
	eMETERTYPE_NORMAL,                //  26 eMID_OLYspeaker1_LF_KLIMITER_OUT
	eMETERTYPE_DYNEQGAIN,             //  27 eMID_OLYspeaker1_HF_DYNEQ1_GAIN
	eMETERTYPE_DYNEQGAIN,             //  28 eMID_OLYspeaker1_HF_DYNEQ2_GAIN
	eMETERTYPE_DYNEQGAIN,             //  29 eMID_OLYspeaker1_MF_DYNEQ1_GAIN
	eMETERTYPE_DYNEQGAIN,             //  30 eMID_OLYspeaker1_MF_DYNEQ2_GAIN
	eMETERTYPE_DYNEQGAIN,             //  31 eMID_OLYspeaker1_LF_DYNEQ1_GAIN
	eMETERTYPE_DYNEQGAIN,             //  32 eMID_OLYspeaker1_LF_DYNEQ2_GAIN
	eMETERTYPE_NORMAL,                //  33 eMID_OLYspeaker1_INPUT_GATE_IN
	eMETERTYPE_GATEGAINRED,           //  34 eMID_OLYspeaker1_INPUT_GATE_GAINREDUCE
	eMETERTYPE_NORMAL,                //  35 eMID_OLYspeaker1_INPUT_GATE_OUT
};

