// DO NOT EDIT THIS FILE
// Created by xmlerator on Tuesday, 02 June 2015 at 02:28:19 PM.

#ifndef __REDLINE_META_H__
#define __REDLINE_META_H__
#include "OLY_Meta.h"

#define eTARGET_GLOBAL		(eTARGET_FENCE+0)
#define eTARGET_SNAPSHOT	(eTARGET_FENCE+1)
/*
typedef enum {
	eTARGET_INVALID = -1,
	eTARGET_CURRENT_STATE = 0,
	eTARGET_METERS,
	eTARGET_GLOBAL,
	eTARGET_SNAPSHOT,
	eTARGET_FIR,
	eTARGET_FENCE
} REDLINE_target;
*/
//typedef enum {
//	eFORMAT_INVALID = -1,
//	eFORMAT_FLOAT,
//	eFORMAT_SIGNED,
//	eFORMAT_UNSIGNED,
//	eFORMAT_BOOL,
//	eFORMAT_STRING,
//	eFORMAT_FENCE
//} REDLINE_format;
/*
typedef struct {
	int      pid;
	unsigned default_value;
} parameter_initializer;
*/
#endif	// __REDLINE_META_H__
