// DO NOT EDIT THIS FILE
// Created by xmlerator on Monday, 01 June 2015 at 07:07:38 PM.
#define REDLINEspeaker1_XML_VERSION 7



#include "REDLINE_meta.h"
#include "../LOUD_enums.h"
#include "REDLINEspeaker1_meter.h"

LOUD_metertype g_REDLINEspeaker1MeterTypeTable[REDLINEspeaker1_METER_MAX] = {
	eMETERTYPE_NORMAL,				  //   0 eMID_REDLINEspeaker1_NULL
	eMETERTYPE_NORMAL,                //   1 eMID_REDLINEspeaker1_INPUT_IN
	eMETERTYPE_NORMAL,                //   2 eMID_REDLINEspeaker1_HF_OUT
	eMETERTYPE_NORMAL,                //   3 eMID_REDLINEspeaker1_HF_SOFTLIMIT_IN
	eMETERTYPE_COMPGAINRED,           //   4 eMID_REDLINEspeaker1_HF_SOFTLIMIT_GAINREDUCE
	eMETERTYPE_NORMAL,                //   5 eMID_REDLINEspeaker1_HF_SOFTLIMIT_OUT
	eMETERTYPE_NORMAL,                //   6 eMID_REDLINEspeaker1_MF_OUT
	eMETERTYPE_NORMAL,                //   7 eMID_REDLINEspeaker1_MF_SOFTLIMIT_IN
	eMETERTYPE_COMPGAINRED,           //   8 eMID_REDLINEspeaker1_MF_SOFTLIMIT_GAINREDUCE
	eMETERTYPE_NORMAL,                //   9 eMID_REDLINEspeaker1_MF_SOFTLIMIT_OUT
};

