// DO NOT EDIT THIS FILE
// Created by xmlerator on Monday, 01 June 2015 at 07:07:38 PM.
#define REDLINEspeaker1_XML_VERSION 7

#ifndef __REDLINEspeaker1_METER_H__
#define __REDLINEspeaker1_METER_H__

#include "LOUD_enums.h"
#include "REDLINEspeaker1_pids.h"

extern LOUD_metertype g_REDLINEspeaker1MeterTypeTable[];
#define REDLINEspeaker1_METER_MAX  eMID_REDLINEspeaker1_FENCE

#endif	// __REDLINEspeaker1_METER_H__
