// DO NOT EDIT THIS FILE
// Created by xmlerator on Tuesday, 23 August 2016 at 04:12:29 PM.
#define OLYspeaker1_XML_VERSION 18

#ifndef __OLYspeaker1_MAP_H__
#define __OLYspeaker1_MAP_H__

#include "OLYspeaker1_arch.h"
#include "OLYspeaker1_pids.h"

#ifdef WIN32							
#define SHOWNAMES 1					
#define COMPACT_DESCRIPTOR 0			
#else									
#define SHOWNAMES 0					
#define COMPACT_DESCRIPTOR 1			
#endif								

typedef struct {						
#if(SHOWNAMES)						
	char             pName[50];			
#endif								
#if(!COMPACT_DESCRIPTOR)				
	OLYspeaker1_type      typeEnum;			
	unsigned short   typeInstance;		
	OLYspeaker1_effect    effectEnum;		
	unsigned short   effectInstance;	
	OLYspeaker1_qualifier qualEnum;			
	unsigned short   qualInstance;		
	OLYspeaker1_parameter paramEnum;			
	unsigned int     linkedChannelPID;
	unsigned int     linkedEffectPID;
#endif								
	unsigned short   format;			
	unsigned int     minValue;			
	unsigned int     maxValue;			
	unsigned int     defValue;			
} OLYspeaker1_parameter_descriptor;		

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1DeviceParameterTable[];
#define OLYspeaker1_DEVICE_PARAMETER_MAX  ePID_OLYspeaker1_DEVICE_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1StatusParameterTable[];
#define OLYspeaker1_STATUS_PARAMETER_MAX  ePID_OLYspeaker1_STATUS_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1UserParameterTable[];
#define OLYspeaker1_USER_PARAMETER_MAX  ePID_OLYspeaker1_USER_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1ProfileParameterTable[];
#define OLYspeaker1_PROFILE_PARAMETER_MAX  ePID_OLYspeaker1_PROFILE_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1ThrowParameterTable[];
#define OLYspeaker1_THROW_PARAMETER_MAX  ePID_OLYspeaker1_THROW_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1VoicingParameterTable[];
#define OLYspeaker1_VOICING_PARAMETER_MAX  ePID_OLYspeaker1_VOICING_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1FirParameterTable[];
#define OLYspeaker1_FIR_PARAMETER_MAX  ePID_OLYspeaker1_FIR_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1XoverParameterTable[];
#define OLYspeaker1_XOVER_PARAMETER_MAX  ePID_OLYspeaker1_XOVER_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1AirlossParameterTable[];
#define OLYspeaker1_AIRLOSS_PARAMETER_MAX  ePID_OLYspeaker1_AIRLOSS_FENCE

extern const OLYspeaker1_parameter_descriptor gOLYspeaker1NoisegateParameterTable[];
#define OLYspeaker1_NOISEGATE_PARAMETER_MAX  ePID_OLYspeaker1_NOISEGATE_FENCE

#endif	// __OLYspeaker1_MAP_H__
