// DO NOT EDIT THIS FILE
// Created by xmlerator on Friday, 12 December 2014 at 06:05:53 PM.
#define OLYmixer1_XML_VERSION 7

#ifndef __OLYmixer1_MAP_H__
#define __OLYmixer1_MAP_H__

#include "OLYmixer1_arch.h"
#include "OLYmixer1_pids.h"

#ifdef WIN32							
#define SHOWNAMES 1					
#else									
#define SHOWNAMES 0					
#endif								

typedef struct {						
#if(SHOWNAMES)						
	char             pName[50];			
#endif								
	OLYmixer1_type      typeEnum;			
	unsigned short   typeInstance;		
	OLYmixer1_effect    effectEnum;		
	unsigned short   effectInstance;	
	OLYmixer1_qualifier qualEnum;			
	unsigned short   qualInstance;		
	OLYmixer1_parameter paramEnum;			
	unsigned int     linkedChannelPID;
	unsigned int     linkedEffectPID;
	unsigned short   format;			
	unsigned int     minValue;			
	unsigned int     maxValue;			
	unsigned int     defValue;			
} OLYmixer1_parameter_descriptor;		

typedef struct {						
#if(SHOWNAMES)						
	char             pName[50];			
#endif								
	OLYmixer1_type      typeEnum;			
	unsigned short   typeInstance;		
	OLYmixer1_effect    effectEnum;		
	unsigned short   effectInstance;	
	OLYmixer1_qualifier qualEnum;			
	unsigned short   qualInstance;		
	OLYmixer1_parameter paramEnum;			
	unsigned int     linkedChannelPID;
	unsigned int     linkedEffectPID;
	unsigned short   format;			
	char             defString[63];		
} OLYmixer1_label_descriptor;		

extern OLYmixer1_parameter_descriptor gOLYmixer1GlobalParameterTable[];
#define OLYmixer1_GLOBAL_PARAMETER_MAX  ePID_OLYmixer1_GLOBAL_FENCE

extern OLYmixer1_parameter_descriptor gOLYmixer1ShowParameterTable[];
#define OLYmixer1_SHOW_PARAMETER_MAX  ePID_OLYmixer1_SHOW_FENCE

extern OLYmixer1_parameter_descriptor gOLYmixer1InfoParameterTable[];
#define OLYmixer1_INFO_PARAMETER_MAX  ePID_OLYmixer1_INFO_FENCE

extern OLYmixer1_parameter_descriptor gOLYmixer1SnapshotParameterTable[];
#define OLYmixer1_SNAPSHOT_PARAMETER_MAX  ePID_OLYmixer1_SNAPSHOT_FENCE

extern OLYmixer1_label_descriptor gOLYmixer1GlobalLabelParameterTable[];
#define OLYmixer1_GLOBAL_LABEL_PARAMETER_MAX  eLID_OLYmixer1_GLOBAL_FENCE

extern OLYmixer1_label_descriptor gOLYmixer1SnapshotLabelParameterTable[];
#define OLYmixer1_SNAPSHOT_LABEL_PARAMETER_MAX  eLID_OLYmixer1_SNAPSHOT_FENCE

#endif	// __OLYmixer1_MAP_H__
