// DO NOT EDIT THIS FILE
// Created by xmlerator on Friday, 12 December 2014 at 06:05:53 PM.
#define OLYmixer1_XML_VERSION 7

#ifndef __OLYmixer1_METER_H__
#define __OLYmixer1_METER_H__

#include "LOUD_enums.h"
#include "OLYmixer1_pids.h"

extern LOUD_metertype g_OLYmixer1MeterTypeTable[];
#define OLYmixer1_METER_MAX  eMID_OLYmixer1_FENCE

#endif	// __OLYmixer1_METER_H__
