/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : spi_sharc.h
**     Project     : oly_host_application
**     Processor   : MK64FN1M0VMD12
**     Component   : fsl_dspi
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-05-14, 11:29, # CodeGen: 2
**     Contents    :
**         DSPI_DRV_IRQHandler              - void DSPI_DRV_IRQHandler(uint32_t instance);
**         DSPI_DRV_MasterInit              - dspi_status_t DSPI_DRV_MasterInit(uint32_t instance,dspi_master_state_t *...
**         DSPI_DRV_MasterDeinit            - dspi_status_t DSPI_DRV_MasterDeinit(uint32_t instance);
**         DSPI_DRV_MasterSetDelay          - dspi_status_t DSPI_DRV_MasterSetDelay(uint32_t instance,dspi_delay_type_t...
**         DSPI_DRV_MasterConfigureBus      - dspi_status_t DSPI_DRV_MasterConfigureBus(uint32_t instance,const...
**         DSPI_DRV_MasterTransferBlocking  - dspi_status_t DSPI_DRV_MasterTransferBlocking(uint32_t instance,const...
**         DSPI_DRV_MasterTransfer          - dspi_status_t DSPI_DRV_MasterTransfer(uint32_t instance,const dspi_device_t *...
**         DSPI_DRV_MasterGetTransferStatus - dspi_status_t DSPI_DRV_MasterGetTransferStatus(uint32_t instance,uint32_t *...
**         DSPI_DRV_MasterAbortTransfer     - dspi_status_t DSPI_DRV_MasterAbortTransfer(uint32_t instance);
**         DSPI_DRV_MasterIRQHandler        - void DSPI_DRV_MasterIRQHandler(uint32_t instance);
**         DSPI_DRV_SlaveInit               - dspi_status_t DSPI_DRV_SlaveInit(uint32_t instance,dspi_slave_state_t *...
**         DSPI_DRV_SlaveDeinit             - dspi_status_t DSPI_DRV_SlaveDeinit(uint32_t instance);
**         DSPI_DRV_SlaveTransferBlocking   - dspi_status_t DSPI_DRV_SlaveTransferBlocking(uint32_t instance,const uint8_t...
**         DSPI_DRV_SlaveTransfer           - dspi_status_t DSPI_DRV_SlaveTransfer(uint32_t instance,const uint8_t *...
**         DSPI_DRV_SlaveAbortTransfer      - dspi_status_t DSPI_DRV_SlaveAbortTransfer(uint32_t instance);
**         DSPI_DRV_SlaveGetTransferStatus  - dspi_status_t DSPI_DRV_SlaveGetTransferStatus(uint32_t instance,uint32_t *...
**         DSPI_DRV_SlaveIRQHandler         - void DSPI_DRV_SlaveIRQHandler(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file spi_sharc.h
** @version 01.00
*/         
/*!
**  @addtogroup spi_sharc_module spi_sharc module documentation
**  @{
*/         
#ifndef __spi_sharc_H
#define __spi_sharc_H
/* MODULE spi_sharc. */

#include "fsl_dspi_master_driver.h"
#include "fsl_dspi_shared_function.h"

/*! @brief Device instance number */
#define FSL_SPI_SHARC 0
/*! @brief spi_sharc component mode */
#define SPI_SHARC_DMA_MODE 0U

/*! @brief Driver state structure. Generated due to enabled auto initialization */
extern dspi_master_state_t spi_sharc_MasterState;

/*! @brief Driver calculated baudrate is returned from DSPI_DRV_MasterInit() call.
    Generated due to enabled auto initialization */
extern uint32_t spi_sharc_calculatedBaudRate;
  
/*! @brief Master bus configuration declaration */
extern const dspi_device_t spi_sharc_bootConfig;
extern const dspi_device_t spi_sharc_hostConfig;
    
/*! @brief Master configuration declaration */
extern const dspi_master_user_config_t spi_sharc_MasterConfig_boot;
extern const dspi_master_user_config_t spi_sharc_MasterConfig_host;

void spi_sharc_IRQHandler(void);
void dsp_sharc_SetMode_Host(void);
    
#endif
/* ifndef __spi_sharc_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
