/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : spi_sharc.c
**     Project     : oly_host_application
**     Processor   : MK64FN1M0VMD12
**     Component   : fsl_dspi
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-07-30, 12:17, # CodeGen: 121
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file spi_sharc.c
** @version 01.00
*/         
/*!
**  @addtogroup spi_sharc_module spi_sharc module documentation
**  @{
*/         

/* spi_sharc. */

#include "spi_sharc.h"

dspi_master_state_t spi_sharc_MasterState;
uint32_t spi_sharc_calculatedBaudRate = 0;
  
const dspi_device_t spi_sharc_bootConfig = {
  .bitsPerSec = 535714U,
  .dataBusConfig.bitsPerFrame = 8U,
  .dataBusConfig.clkPolarity = kDspiClockPolarity_ActiveLow,
  .dataBusConfig.clkPhase = kDspiClockPhase_SecondEdge,
  .dataBusConfig.direction = kDspiLsbFirst,
};

const dspi_device_t spi_sharc_hostConfig = {
  .bitsPerSec = 6000000U,
  .dataBusConfig.bitsPerFrame = 16U,
  .dataBusConfig.clkPolarity = kDspiClockPolarity_ActiveLow,
  .dataBusConfig.clkPhase = kDspiClockPhase_SecondEdge,
  .dataBusConfig.direction = kDspiMsbFirst,
};

const dspi_master_user_config_t spi_sharc_MasterConfig_boot = {
  .whichCtar = kDspiCtar0,
  .isSckContinuous = false,
  .isChipSelectContinuous = true,
  .whichPcs = kDspiPcs0,
  .pcsPolarity = kDspiPcs_ActiveLow,
};

const dspi_master_user_config_t spi_sharc_MasterConfig_host = {
  .whichCtar = kDspiCtar0,
  .isSckContinuous = false,
  .isChipSelectContinuous = true,
  .whichPcs = kDspiPcs0,
  .pcsPolarity = kDspiPcs_ActiveLow,
};

void dsp_sharc_SetMode_Host(void)
{
	dspi_status_t 	dsp_result;
	uint8_t return_status;
	uint32_t retval;

	do{
		dsp_result = DSPI_DRV_MasterDeinit(FSL_SPI_SHARC);
		return_status = *(uint8_t*) &dsp_result;
	} while(return_status);

	OSA_InstallIntHandler(SPI0_IRQn, spi_sharc_IRQHandler);

	DSPI_DRV_MasterInit(FSL_SPI_SHARC, &spi_sharc_MasterState, &spi_sharc_MasterConfig_host);

	DSPI_DRV_MasterConfigureBus(FSL_SPI_SHARC, &spi_sharc_hostConfig, &spi_sharc_calculatedBaudRate);
    DSPI_DRV_MasterSetDelay(FSL_SPI_SHARC, kDspiPcsToSck, 64, &retval);
    DSPI_DRV_MasterSetDelay(FSL_SPI_SHARC, kDspiLastSckToPcs, 64, &retval);

}

void spi_sharc_IRQHandler(void)
{
  DSPI_DRV_IRQHandler(FSL_SPI_SHARC);
}


/* END spi_sharc. */

