#ifndef __PRODUCT_ARCH_H__
#define __PRODUCT_ARCH_H__

#include "OLYSpeaker1_arch.h"

#define eEFFECT_HPF			(eEFFECT_FENCE+0)
#define eEFFECT_LPF			(eEFFECT_FENCE+1)
#define ePARAM_SLOPE		(ePARAM_FENCE+0)
#define ePARAM_RESPONSE		(ePARAM_FENCE+1)

/*
typedef enum {
	eTYPE_INVALID = -1,
	eTYPE_NULL,
	eTYPE_INPUT,
	eTYPE_USER,
	eTYPE_GROUP,
	eTYPE_PROFILE,
	eTYPE_THROW,
	eTYPE_GLOBAL,
	eTYPE_HF,
	eTYPE_MF,
	eTYPE_LF,
	eTYPE_AMP,
	eTYPE_FENCE
} OLYspeaker1_type;

typedef enum {
	eEFFECT_INVALID = -1,
	eEFFECT_NULL,
	eEFFECT_FUNCGEN,
	eEFFECT_XOVER,
	eEFFECT_PEQ,
	eEFFECT_DELAY,
	eEFFECT_SOFTLIMIT,
	eEFFECT_SUBHARMONICS,
	eEFFECT_HPF,
	eEFFECT_LPF,
	eEFFECT_FIR,
	eEFFECT_KLIMITER,
	eEFFECT_PEQ_POST,
	eEFFECT_DYNEQ,
	eEFFECT_EXCITER,
	eEFFECT_EXCITER_GATE,
	eEFFECT_EXCITER_PEQ,
	eEFFECT_FENCE
} OLYspeaker1_effect;

typedef enum {
	eQUAL_INVALID = -1,
	eQUAL_NULL,
	eQUAL_BAND,
	eQUAL_COEF,
	eQUAL_FENCE
} OLYspeaker1_qualifier;

typedef enum {
	ePARAM_INVALID = -1,
	ePARAM_NULL,
	ePARAM_OLY_MODEL,
	ePARAM_LED_MODE,
	ePARAM_AMP1_INVERT,
	ePARAM_AMP2_INVERT,
	ePARAM_AMP3_INVERT,
	ePARAM_AMP4_INVERT,
	ePARAM_ENABLE,
	ePARAM_FADER,
	ePARAM_TYPE,
	ePARAM_FREQ,
	ePARAM_ROUTING,
	ePARAM_INVERT,
	ePARAM_GAIN,
	ePARAM_THRESH,
	ePARAM_ATTACK,
	ePARAM_RELEASE,
	ePARAM_RATIO,
	ePARAM_KNEE,
	ePARAM_Q,
	ePARAM_TIME,
	ePARAM_MUTE,
	ePARAM_SLOPE,
	ePARAM_RESPONSE,
	ePARAM_VALUE,
	ePARAM_PEAKENABLE,
	ePARAM_PEAKATTACK,
	ePARAM_GAINRELEASE,
	ePARAM_LOOKAHEAD,
	ePARAM_MAXPEAK,
	ePARAM_CLIPENABLE,
	ePARAM_CLIPATTACK,
	ePARAM_CLIPRELEASE,
	ePARAM_CLIPTHRESHOLD,
	ePARAM_FADER_POST,
	ePARAM_MUTE_POST,
	ePARAM_HPFFREQ,
	ePARAM_HPFSLOPE,
	ePARAM_LPFFREQ,
	ePARAM_LPFSLOPE,
	ePARAM_DETECTEN,
	ePARAM_DETECTTYPE,
	ePARAM_DETECTGAIN,
	ePARAM_DETECTFREQ,
	ePARAM_DETECTQ,
	ePARAM_AGCENABLE,
	ePARAM_AGCATTACK,
	ePARAM_AGCDECAY,
	ePARAM_AGCACTIVE,
	ePARAM_AGCTHRESH,
	ePARAM_AGCRATIO,
	ePARAM_RESUMEN,
	ePARAM_RESUMTYPE,
	ePARAM_RESUMGAIN,
	ePARAM_RESUMFREQ,
	ePARAM_RESUMQ,
	ePARAM_RANGE,
	ePARAM_HOLD,
	ePARAM_FENCE
} OLYspeaker1_parameter;
*/
#endif	// __PRODUCT_ARCH_H__
