// DO NOT EDIT THIS FILE
// Created by xmlerator on Tuesday, 23 August 2016 at 04:12:29 PM.

#ifndef __OLY_META_H__
#define __OLY_META_H__

typedef enum {
	eTARGET_INVALID = -1,
	eTARGET_CURRENT_STATE = 0,
	eTARGET_METERS,
	eTARGET_DEVICE,
	eTARGET_STATUS,
	eTARGET_USER,
	eTARGET_PROFILE,
	eTARGET_THROW,
	eTARGET_VOICING,
	eTARGET_FIR,
	eTARGET_XOVER,
	eTARGET_AIRLOSS,
	eTARGET_NOISEGATE,
	eTARGET_FENCE
} OLY_target;

typedef enum {
	eFORMAT_INVALID = -1,
	eFORMAT_FLOAT,
	eFORMAT_SIGNED,
	eFORMAT_UNSIGNED,
	eFORMAT_BOOL,
	eFORMAT_STRING,
	eFORMAT_FENCE
} OLY_format;

typedef struct {
	int      pid;
	unsigned default_value;
} parameter_initializer;

#endif	// __OLY_META_H__
