// DO NOT EDIT THIS FILE
// Created by xmlerator on Tuesday, 23 August 2016 at 04:12:29 PM.
#define OLYspeaker1_XML_VERSION 18

#ifndef __OLYspeaker1_METER_H__
#define __OLYspeaker1_METER_H__

#include "LOUD_enums.h"
#include "OLYspeaker1_pids.h"

extern LOUD_metertype g_OLYspeaker1MeterTypeTable[];
#define OLYspeaker1_METER_MAX  eMID_OLYspeaker1_FENCE

#endif	// __OLYspeaker1_METER_H__
